# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
a=np.zeros(10)
print (a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [6]:
arrayone=np.ones(10)
print(arrayone)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [9]:
a=np.full((1,10),5)
print(a)

[[5 5 5 5 5 5 5 5 5 5]]


#### Create an array of the integers from 10 to 50

In [12]:
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [38]:
b=a%2==0
d=a [b]
print(d)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [57]:
c=np.arange(0,9).reshape(3,3)
print(c )

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [59]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [62]:
a=np.random.random()
a=[a]
a=np.array(a)
print(a)

[0.70495255]


array([ 0.42829726])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
#np.random.normal(0, 1, 25)
#np.random.randn(25) # [0-1]

In [63]:
a=np.random.normal(0,1,25)
print(a)

[-0.34868283 -0.90349525  1.19562357 -0.79187721 -1.70777975 -0.53526123
  0.71555244  0.91585632 -2.72911564 -0.13356493 -1.39726517  0.54518462
  1.5049349  -0.25847709 -0.49688627 -0.68590072  1.21949122  0.049808
 -1.27069335  0.52800475 -0.9151102   0.9255802   0.51543563 -0.20295752
  1.87466268]


#### Create the following matrix:

In [67]:
a=np.random.randn(25)
print(a)

[-1.02376912 -0.86157869 -0.85751391  0.84065083  0.53477779 -0.14232399
 -2.18039906  1.6374371  -0.02697244  1.15113364  0.12513384 -0.44345857
 -0.76573228  1.81262997  0.46937274 -0.98901412  0.23053079  0.20143746
 -0.80996459 -0.80131284  0.23336914  0.90947934 -0.90243124 -0.04700722
  1.41710683]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [68]:
a=np.linspace(0,1,20)
print(a)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [78]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [97]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [98]:
mat[3][4]

20

In [99]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [100]:
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [101]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [79]:
a=np.sum(mat)
print(a)

325


325

#### Get the standard deviation of the values in mat

In [81]:
a=np.std(mat)
a

7.211102550927978

7.2111025509279782

#### Get the sum of all the columns in mat

In [84]:
a=np.sum(mat,axis=0)
a

array([55, 60, 65, 70, 75])

array([55, 60, 65, 70, 75])

# Great Job!